// <copyright file="Achievements.cs" company="Trollpants Game Studio AS">
// Copyright (c) 2016 Trollpants Game Studio AS. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Trollpants.CloudOnce
{
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_starterpack = new UnifiedAchievement("Starterpack",
#if !UNITY_EDITOR && UNITY_IOS
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidGoogle
            "CgkI-Meyi84DEAIQAA"
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidAmazon
            ""
#else
            "Starterpack"
#endif
            );

        public static UnifiedAchievement Starterpack
        {
            get { return s_starterpack; }
        }

        private static readonly UnifiedAchievement s_notanoob = new UnifiedAchievement("Notanoob",
#if !UNITY_EDITOR && UNITY_IOS
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidGoogle
            "CgkI-Meyi84DEAIQAQ"
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidAmazon
            ""
#else
            "Notanoob"
#endif
            );

        public static UnifiedAchievement Notanoob
        {
            get { return s_notanoob; }
        }

        private static readonly UnifiedAchievement s_givememore = new UnifiedAchievement("Givememore",
#if !UNITY_EDITOR && UNITY_IOS
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidGoogle
            "CgkI-Meyi84DEAIQAg"
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidAmazon
            ""
#else
            "Givememore"
#endif
            );

        public static UnifiedAchievement Givememore
        {
            get { return s_givememore; }
        }

        private static readonly UnifiedAchievement s_stuck = new UnifiedAchievement("Stuck",
#if !UNITY_EDITOR && UNITY_IOS
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidGoogle
            "CgkI-Meyi84DEAIQAw"
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidAmazon
            ""
#else
            "Stuck"
#endif
            );

        public static UnifiedAchievement Stuck
        {
            get { return s_stuck; }
        }

        private static readonly UnifiedAchievement s_menuboss = new UnifiedAchievement("Menuboss",
#if !UNITY_EDITOR && UNITY_IOS
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidGoogle
            "CgkI-Meyi84DEAIQBw"
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidAmazon
            ""
#else
            "Menuboss"
#endif
            );

        public static UnifiedAchievement Menuboss
        {
            get { return s_menuboss; }
        }
    }
}
