// <copyright file="CloudVariables.cs" company="Trollpants Game Studio AS">
// Copyright (c) 2016 Trollpants Game Studio AS. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Trollpants.CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudInt s_level = new CloudInt("Level", PersistenceType.Latest, 0);

        public static int Level
        {
            get { return s_level.Value; }
            set { s_level.Value = value; }
        }

        private static readonly CloudString s_timeAndDeaths = new CloudString("TimeAndDeaths", PersistenceType.Latest, "0");

        public static string TimeAndDeaths
        {
            get { return s_timeAndDeaths.Value; }
            set { s_timeAndDeaths.Value = value; }
        }

        private static readonly CloudBool s_isFirstTime = new CloudBool("isFirstTime", PersistenceType.Latest, true);

        public static bool isFirstTime
        {
            get { return s_isFirstTime.Value; }
            set { s_isFirstTime.Value = value; }
        }
    }
}
