// <copyright file="CloudIDs.cs" company="Trollpants Game Studio AS">
// Copyright (c) 2016 Trollpants Game Studio AS. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Trollpants.CloudOnce
{
#if (UNITY_ANDROID || UNITY_IOS) && !UNITY_EDITOR
    using Internal;
    using UnityEngine;
#endif
    /// <summary>
    /// Provides access to achievement- and leaderboard IDs registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudIDs
    {
        /// <summary>
        /// Contains properties that retrieves achievement IDs for the current platform.
        /// </summary>
        public static class AchievementIDs
        {
            public static string Starterpack
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if TP_AndroidAmazon
                    return "";
#elif TP_AndroidGoogle
                    return "CgkI-Meyi84DEAIQAA";
#else
                    return string.Empty;
#endif
#elif UNITY_IOS && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Starterpack";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Notanoob
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if TP_AndroidAmazon
                    return "";
#elif TP_AndroidGoogle
                    return "CgkI-Meyi84DEAIQAQ";
#else
                    return string.Empty;
#endif
#elif UNITY_IOS && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Notanoob";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Givememore
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if TP_AndroidAmazon
                    return "";
#elif TP_AndroidGoogle
                    return "CgkI-Meyi84DEAIQAg";
#else
                    return string.Empty;
#endif
#elif UNITY_IOS && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Givememore";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Stuck
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if TP_AndroidAmazon
                    return "";
#elif TP_AndroidGoogle
                    return "CgkI-Meyi84DEAIQAw";
#else
                    return string.Empty;
#endif
#elif UNITY_IOS && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Stuck";
#else
                    return string.Empty;
#endif
                }
            }

            public static string Menuboss
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if TP_AndroidAmazon
                    return "";
#elif TP_AndroidGoogle
                    return "CgkI-Meyi84DEAIQBw";
#else
                    return string.Empty;
#endif
#elif UNITY_IOS && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "Menuboss";
#else
                    return string.Empty;
#endif
                }
            }
        }

        /// <summary>
        /// Contains properties that retrieves leaderboard IDs for the current platform.
        /// </summary>
        public static class LeaderboardIDs
        {
            public static string test
            {
                get
                {
#if UNITY_ANDROID && !UNITY_EDITOR
#if TP_AndroidAmazon
                    return "";
#elif TP_AndroidGoogle
                    return "CgkI-Meyi84DEAIQBg";
#else
                    return string.Empty;
#endif
#elif UNITY_IOS && !UNITY_EDITOR
                    return "";
#elif UNITY_EDITOR
                    return "test";
#else
                    return string.Empty;
#endif
                }
            }
        }
    }
}
