// <copyright file="Leaderboards.cs" company="Trollpants Game Studio AS">
// Copyright (c) 2016 Trollpants Game Studio AS. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace Trollpants.CloudOnce
{
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_test = new UnifiedLeaderboard("test",
#if !UNITY_EDITOR && UNITY_IOS
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidGoogle
            "CgkI-Meyi84DEAIQBg"
#elif !UNITY_EDITOR && UNITY_ANDROID && TP_AndroidAmazon
            ""
#else
            "test"
#endif
            );

        public static UnifiedLeaderboard test
        {
            get { return s_test; }
        }
    }
}
